apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detector
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
        - name: detector
          image: deployments-detector:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret