apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: deployments-billing:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret