// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: billing/v1/billing.proto

package billingv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLimitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitsRequest) Reset() {
	*x = GetLimitsRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitsRequest) ProtoMessage() {}

func (x *GetLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitsRequest.ProtoReflect.Descriptor instead.
func (*GetLimitsRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *GetLimitsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetLimitsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PlanName           string                 `protobuf:"bytes,1,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	MaxMonitors        int32                  `protobuf:"varint,2,opt,name=max_monitors,json=maxMonitors,proto3" json:"max_monitors,omitempty"`
	MinIntervalSeconds int32                  `protobuf:"varint,3,opt,name=min_interval_seconds,json=minIntervalSeconds,proto3" json:"min_interval_seconds,omitempty"`
	RateLimitPerMinute int32                  `protobuf:"varint,4,opt,name=rate_limit_per_minute,json=rateLimitPerMinute,proto3" json:"rate_limit_per_minute,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetLimitsResponse) Reset() {
	*x = GetLimitsResponse{}
	mi := &file_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitsResponse) ProtoMessage() {}

func (x *GetLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitsResponse.ProtoReflect.Descriptor instead.
func (*GetLimitsResponse) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *GetLimitsResponse) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *GetLimitsResponse) GetMaxMonitors() int32 {
	if x != nil {
		return x.MaxMonitors
	}
	return 0
}

func (x *GetLimitsResponse) GetMinIntervalSeconds() int32 {
	if x != nil {
		return x.MinIntervalSeconds
	}
	return 0
}

func (x *GetLimitsResponse) GetRateLimitPerMinute() int32 {
	if x != nil {
		return x.RateLimitPerMinute
	}
	return 0
}

var File_billing_v1_billing_proto protoreflect.FileDescriptor

const file_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x18billing/v1/billing.proto\x12\n" +
	"billing.v1\"+\n" +
	"\x10GetLimitsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xb8\x01\n" +
	"\x11GetLimitsResponse\x12\x1b\n" +
	"\tplan_name\x18\x01 \x01(\tR\bplanName\x12!\n" +
	"\fmax_monitors\x18\x02 \x01(\x05R\vmaxMonitors\x120\n" +
	"\x14min_interval_seconds\x18\x03 \x01(\x05R\x12minIntervalSeconds\x121\n" +
	"\x15rate_limit_per_minute\x18\x04 \x01(\x05R\x12rateLimitPerMinute2Z\n" +
	"\x0eBillingService\x12H\n" +
	"\tGetLimits\x12\x1c.billing.v1.GetLimitsRequest\x1a\x1d.billing.v1.GetLimitsResponseB;Z9github.com/Bremcm/uptime/internal/pb/billing/v1;billingv1b\x06proto3"

var (
	file_billing_v1_billing_proto_rawDescOnce sync.Once
	file_billing_v1_billing_proto_rawDescData []byte
)

func file_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_v1_billing_proto_rawDesc), len(file_billing_v1_billing_proto_rawDesc)))
	})
	return file_billing_v1_billing_proto_rawDescData
}

var file_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_billing_v1_billing_proto_goTypes = []any{
	(*GetLimitsRequest)(nil),  // 0: billing.v1.GetLimitsRequest
	(*GetLimitsResponse)(nil), // 1: billing.v1.GetLimitsResponse
}
var file_billing_v1_billing_proto_depIdxs = []int32{
	0, // 0: billing.v1.BillingService.GetLimits:input_type -> billing.v1.GetLimitsRequest
	1, // 1: billing.v1.BillingService.GetLimits:output_type -> billing.v1.GetLimitsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_v1_billing_proto_init() }
func file_billing_v1_billing_proto_init() {
	if File_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_v1_billing_proto_rawDesc), len(file_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_billing_v1_billing_proto = out.File
	file_billing_v1_billing_proto_goTypes = nil
	file_billing_v1_billing_proto_depIdxs = nil
}
