apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: deployments-notifier:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret