apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archiver
  template:
    metadata:
      labels:
        app: archiver
    spec:
      containers:
        - name: archiver
          image: deployments-archiver:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: common-secret