apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  DATABASE_URL: "postgres://uptime:postgres123test@postgres:5432/uptime?sslmode=disable"
  KAFKA_BROKERS: "kafka:9092"
  HTTP_ADDR: ":8080"
  CLICKHOUSE_ADDR: "clickhouse:9000"
  REDIS_ADDR: "redis:6379"
  BILLING_GRPC_ADDR: "billing:50051"
  JAEGER_ADDR: "jaeger:4317"
  BILLING_GRPC_ADDR: ":50051"
  BILLING_CLIENT_ADDR: "billing:50051"